# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 569)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "QWidget {\n"
            "    background-color: #F8F9FA;\n"
            "}\n"
            "\n"
            "QLineEdit, QDateEdit, QComboBox {\n"
            "    background-color: #FFFFFF;\n"
            "    border: 1px solid #D0D0D0;\n"
            "    color: #37474F;\n"
            "    padding: 5px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "\n"
            "QLineEdit:focus, QDateEdit:focus, QComboBox:focus {\n"
            "    border: 1px solid #81D4FA;\n"
            "    outline: none;\n"
            "}\n"
            "QLabel {\n"
            "    color: #607D8B;\n"
            "    font-weight: bold;\n"
            "}\n"
            "QMessageBox {\n"
            "    background-color: #FFFFFF;\n"
            "    color: #37474F;\n"
            "}\n"
            "\n"
            ""
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 981, 521))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.master_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.master_layout.setContentsMargins(0, 0, 0, 0)
        self.master_layout.setObjectName("master_layout")
        self.row_1 = QtWidgets.QHBoxLayout()
        self.row_1.setObjectName("row_1")
        self.searchEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.searchEdit.setObjectName("searchEdit")
        self.row_1.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.searchButton.setStyleSheet(
            "QPushButton#searchButton {\n"
            "    background-color: #81D4FA;\n"
            "    color: #37474F;\n"
            "    border: none;\n"
            "    padding: 8px 15px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QPushButton#searchButton:hover {\n"
            "    background-color: #4FC3F7;\n"
            "}\n"
            ""
        )
        self.searchButton.setObjectName("searchButton")
        self.row_1.addWidget(self.searchButton)
        self.master_layout.addLayout(self.row_1)
        self.row_2 = QtWidgets.QHBoxLayout()
        self.row_2.setObjectName("row_2")
        self.filterCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.filterCheckBox.setStyleSheet(
            "QCheckBox {\n"
            "    color: #607D8B;\n"
            "    spacing: 5px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator {\n"
            "    width: 18px;\n"
            "    height: 18px;\n"
            "    border-radius: 3px;\n"
            "    background-color: #F3F4F6;\n"
            "    border: 1px solid #D0D0D0;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: #81D4FA;\n"
            #     "    image: url(:/checkmark.svg);\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:hover {\n"
            "    border: 1px solid #81D4FA;\n"
            "}\n"
            ""
        )
        self.filterCheckBox.setObjectName("filterCheckBox")
        self.row_2.addWidget(self.filterCheckBox)
        self.filterDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.filterDropdown.setObjectName("filterDropdown")
        self.filterDropdown.addItem("")
        self.filterDropdown.addItem("")
        self.filterDropdown.addItem("")
        self.row_2.addWidget(self.filterDropdown)
        self.filterElementDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.filterElementDropdown.setObjectName("filterElementDropdown")
        self.row_2.addWidget(self.filterElementDropdown)
        self.master_layout.addLayout(self.row_2)
        self.row_3 = QtWidgets.QHBoxLayout()
        self.row_3.setObjectName("row_3")
        self.table = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.table.setStyleSheet(
            "QTableWidget {\n"
            "    background-color: #FFFFFF;\n"
            "    alternate-background-color: #F3F4F6;\n"
            "    gridline-color: #E0E0E0;\n"
            "    color: #37474F;\n"
            "    border: 1px solid #E0E0E0;\n"
            "    selection-background-color: #CCE7FF;\n"
            "}\n"
            "\n"
            "QTableWidget::item {\n"
            "    padding: 10px;\n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QTableWidget::item:selected {\n"
            "    background-color: #CCE7FF;\n"
            "    color: #37474F;\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #E8EAF6;\n"
            "    color: #37474F;\n"
            "}\n"
            "\n"
            "QHeaderView::section {\n"
            "    background-color: #81D4FA;\n"
            "    color: #FFFFFF;\n"
            "    padding: 5px;\n"
            "    border: none;\n"
            "    font-weight: bold;\n"
            "    border-bottom: 2px solid #4FC3F7;\n"
            "}\n"
            "\n"
            "QTableCornerButton::section {\n"
            "    background-color: #81D4FA;\n"
            "    border: none;\n"
            "}\n"
            ""
        )
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)

        # Make columns expand to fit the table width
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch
        )

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)

        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.row_3.addWidget(self.table, 70)

        self.col_1 = QtWidgets.QVBoxLayout()
        self.col_1.setObjectName("col_1")

        self.col_row_1 = QtWidgets.QHBoxLayout()
        self.col_row_1.setObjectName("col_row_1")
        self.sizeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sizeLabel.setObjectName("sizeLabel")
        self.col_row_1.addWidget(self.sizeLabel)
        self.sizeEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sizeEdit.setObjectName("sizeEdit")
        self.col_row_1.addWidget(self.sizeEdit)
        self.col_1.addLayout(self.col_row_1)

        self.col_row_2 = QtWidgets.QHBoxLayout()
        self.col_row_2.setObjectName("col_row_2")
        self.brandLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.brandLabel.setObjectName("brandLabel")
        self.col_row_2.addWidget(self.brandLabel)
        self.brandDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.brandDropdown.setObjectName("brandDropdown")
        self.brandDropdown.addItem("")
        self.col_row_2.addWidget(self.brandDropdown)
        self.col_1.addLayout(self.col_row_2)

        self.col_row_3 = QtWidgets.QHBoxLayout()
        self.col_row_3.setObjectName("col_row_3")
        self.countryLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.countryLabel.setObjectName("countryLabel")
        self.col_row_3.addWidget(self.countryLabel)
        self.countryDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.countryDropdown.setObjectName("countryDropdown")
        self.countryDropdown.addItem("")
        self.col_row_3.addWidget(self.countryDropdown)
        self.col_1.addLayout(self.col_row_3)

        self.col_row_4 = QtWidgets.QHBoxLayout()
        self.col_row_4.setObjectName("col_row_4")
        self.dateLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.dateLabel.setObjectName("dateLabel")
        self.col_row_4.addWidget(self.dateLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.col_row_4.addWidget(self.dateEdit)
        self.col_1.addLayout(self.col_row_4)
        self.col_row_5 = QtWidgets.QHBoxLayout()
        self.col_row_5.setObjectName("col_row_5")
        self.stockLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.stockLabel.setObjectName("stockLabel")
        self.col_row_5.addWidget(self.stockLabel)
        self.stockEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.stockEdit.setObjectName("stockEdit")
        self.col_row_5.addWidget(self.stockEdit)
        self.col_1.addLayout(self.col_row_5)
        self.addButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addButton.setStyleSheet(
            "QPushButton#addButton {\n"
            "    background-color: #A8E6CF;\n"
            "    color: #37474F;\n"
            "    border: none;\n"
            "    padding: 8px 15px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QPushButton#addButton:hover {\n"
            "    background-color: #94D6B9;\n"
            "}\n"
            ""
        )
        self.addButton.setObjectName("addButton")
        self.col_1.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.editButton.setStyleSheet(
            "QPushButton#editButton {\n"
            "    background-color: #FFD3B6;\n"
            "    color: #37474F;\n"
            "    border: none;\n"
            "    padding: 8px 15px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QPushButton#editButton:hover {\n"
            "    background-color: #FFC3A2;\n"
            "}\n"
            ""
        )
        self.editButton.setObjectName("editButton")
        self.col_1.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.deleteButton.setStyleSheet(
            "QPushButton#deleteButton {\n"
            "    background-color: #FF8B94;\n"
            "    color: #FFFFFF;\n"
            "    border: none;\n"
            "    padding: 8px 15px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QPushButton#deleteButton:hover {\n"
            "    background-color: #FF6F7D;\n"
            "}\n"
            ""
        )
        self.deleteButton.setObjectName("deleteButton")
        self.col_1.addWidget(self.deleteButton)
        self.row_3.addLayout(self.col_1, 30)
        self.master_layout.addLayout(self.row_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.filterCheckBox.setText(_translate("MainWindow", "Filter"))

        self.filterDropdown.setItemText(0, _translate("MainWindow", "Year"))
        self.filterDropdown.setItemText(1, _translate("MainWindow", "Brand"))
        self.filterDropdown.setItemText(2, _translate("MainWindow", "Country"))
        self.brandDropdown.setItemText(0, _translate("MainWindow", "Add New Brand ..."))
        self.countryDropdown.setItemText(
            0, _translate("MainWindow", "Add New Country ...")
        )

        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Stock"))

        self.sizeLabel.setText(_translate("MainWindow", "Size"))
        self.brandLabel.setText(_translate("MainWindow", "Brand"))
        self.countryLabel.setText(_translate("MainWindow", "Country"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.stockLabel.setText(_translate("MainWindow", "Stock"))

        self.addButton.setText(_translate("MainWindow", "Add Record"))
        self.editButton.setText(_translate("MainWindow", "Edit Record"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Record"))
