# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    This class represents the main window UI for the application.
    It includes the layout, widgets (e.g., buttons, labels, dropdowns, table),
    and actions for user interactions. It is designed to display and manage records
    for different sizes, brands, countries, and stock information.

    Methods:
        setupUi: Initializes and sets up the main window UI and widgets.
        retranslateUi: Sets the textual content for UI elements in the current language.
    """

    def setupUi(self, MainWindow):
        """
        Initializes the main window's UI components and layout.

        Parameters:
            MainWindow (QMainWindow): The main window that holds all the UI elements.
        """
        # Set the main window's object name and size
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 569)
        MainWindow.setStyleSheet("")

        # Central widget which holds all UI elements
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "QWidget {\n"
            "    background-color: #F8F9FA;\n"
            "}\n"
            "\n"
            "QLineEdit, QDateEdit, QComboBox {\n"
            "    background-color: #FFFFFF;\n"
            "    border: 1px solid #D0D0D0;\n"
            "    color: #37474F;\n"
            "    padding: 5px;\n"
            "    border-radius: 3px;\n"
            "}\n"
            "\n"
            "QLineEdit:focus, QDateEdit:focus, QComboBox:focus {\n"
            "    border: 1px solid #81D4FA;\n"
            "    outline: none;\n"
            "}\n"
            "QLabel {\n"
            "    color: #607D8B;\n"
            "    font-weight: bold;\n"
            "}\n"
            "QMessageBox {\n"
            "    background-color: #FFFFFF;\n"
            "    color: #37474F;\n"
            "}\n"
        )

        # Main layout for the central widget
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 981, 521))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.master_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.master_layout.setContentsMargins(0, 0, 0, 0)
        self.master_layout.setObjectName("master_layout")

        # Row 1: Search input and button
        self.row_1 = QtWidgets.QHBoxLayout()
        self.row_1.setObjectName("row_1")
        self.searchEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.searchEdit.setObjectName("searchEdit")
        self.row_1.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.searchButton.setStyleSheet(
            "QPushButton#searchButton {\n"
            "    background-color: #81D4FA;\n"
            "    color: #37474F;\n"
            "    border: none;\n"
            "    padding: 8px 15px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QPushButton#searchButton:hover {\n"
            "    background-color: #4FC3F7;\n"
            "}\n"
        )
        self.searchButton.setObjectName("searchButton")
        self.row_1.addWidget(self.searchButton)
        self.master_layout.addLayout(self.row_1)

        # Row 2: Filter checkbox, filter dropdown, and filter element dropdown
        self.row_2 = QtWidgets.QHBoxLayout()
        self.row_2.setObjectName("row_2")
        self.filterCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.filterCheckBox.setStyleSheet(
            "QCheckBox {\n"
            "    color: #607D8B;\n"
            "    spacing: 5px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator {\n"
            "    width: 18px;\n"
            "    height: 18px;\n"
            "    border-radius: 3px;\n"
            "    background-color: #F3F4F6;\n"
            "    border: 1px solid #D0D0D0;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: #81D4FA;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:hover {\n"
            "    border: 1px solid #81D4FA;\n"
            "}\n"
        )
        self.filterCheckBox.setObjectName("filterCheckBox")
        self.row_2.addWidget(self.filterCheckBox)

        self.filterDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.filterDropdown.setObjectName("filterDropdown")
        self.filterDropdown.addItem("")
        self.filterDropdown.addItem("")
        self.filterDropdown.addItem("")
        self.row_2.addWidget(self.filterDropdown)

        self.filterElementDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.filterElementDropdown.setObjectName("filterElementDropdown")
        self.row_2.addWidget(self.filterElementDropdown)
        self.master_layout.addLayout(self.row_2)

        # Row 3: Table and column layout
        self.row_3 = QtWidgets.QHBoxLayout()
        self.row_3.setObjectName("row_3")
        self.table = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.table.setStyleSheet(
            "QTableWidget {\n"
            "    background-color: #FFFFFF;\n"
            "    alternate-background-color: #F3F4F6;\n"
            "    gridline-color: #E0E0E0;\n"
            "    color: #37474F;\n"
            "    border: 1px solid #E0E0E0;\n"
            "    selection-background-color: #CCE7FF;\n"
            "}\n"
            "\n"
            "QTableWidget::item {\n"
            "    padding: 10px;\n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QTableWidget::item:selected {\n"
            "    background-color: #CCE7FF;\n"
            "    color: #37474F;\n"
            "}\n"
            "\n"
            "QTableWidget::item:hover {\n"
            "    background-color: #E8EAF6;\n"
            "    color: #37474F;\n"
            "}\n"
            "\n"
            "QHeaderView::section {\n"
            "    background-color: #81D4FA;\n"
            "    color: #FFFFFF;\n"
            "    padding: 5px;\n"
            "    border: none;\n"
            "    font-weight: bold;\n"
            "    border-bottom: 2px solid #4FC3F7;\n"
            "}\n"
            "\n"
            "QTableCornerButton::section {\n"
            "    background-color: #81D4FA;\n"
            "    border: none;\n"
            "}\n"
        )
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)

        # Make columns expand to fit the table width
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch
        )

        # Table headers
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)

        # Adding the table to the layout
        self.row_3.addWidget(self.table, 70)

        # Additional input fields and buttons layout
        self.col_1 = QtWidgets.QVBoxLayout()
        self.col_1.setObjectName("col_1")

        # Size input field
        self.col_row_1 = QtWidgets.QHBoxLayout()
        self.col_row_1.setObjectName("col_row_1")
        self.sizeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sizeLabel.setObjectName("sizeLabel")
        self.col_row_1.addWidget(self.sizeLabel)
        self.sizeEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sizeEdit.setObjectName("sizeEdit")
        self.col_row_1.addWidget(self.sizeEdit)
        self.col_1.addLayout(self.col_row_1)

        # Brand dropdown input field
        self.col_row_2 = QtWidgets.QHBoxLayout()
        self.col_row_2.setObjectName("col_row_2")
        self.brandLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.brandLabel.setObjectName("brandLabel")
        self.col_row_2.addWidget(self.brandLabel)
        self.brandDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.brandDropdown.setObjectName("brandDropdown")
        self.col_row_2.addWidget(self.brandDropdown)
        self.col_1.addLayout(self.col_row_2)

        # Country dropdown input field
        self.col_row_3 = QtWidgets.QHBoxLayout()
        self.col_row_3.setObjectName("col_row_3")
        self.countryLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.countryLabel.setObjectName("countryLabel")
        self.col_row_3.addWidget(self.countryLabel)
        self.countryDropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.countryDropdown.setObjectName("countryDropdown")
        self.col_row_3.addWidget(self.countryDropdown)
        self.col_1.addLayout(self.col_row_3)

        # Date input field
        self.col_row_4 = QtWidgets.QHBoxLayout()
        self.col_row_4.setObjectName("col_row_4")
        self.dateLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.dateLabel.setObjectName("dateLabel")
        self.col_row_4.addWidget(self.dateLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.col_row_4.addWidget(self.dateEdit)
        self.col_1.addLayout(self.col_row_4)

        # Stock input field
        self.col_row_5 = QtWidgets.QHBoxLayout()
        self.col_row_5.setObjectName("col_row_5")
        self.stockLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.stockLabel.setObjectName("stockLabel")
        self.col_row_5.addWidget(self.stockLabel)
        self.stockEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.stockEdit.setObjectName("stockEdit")
        self.col_row_5.addWidget(self.stockEdit)
        self.col_1.addLayout(self.col_row_5)

        # Add, Edit, and Delete buttons
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.addButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addButton.setObjectName("addButton")
        self.buttons_layout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.editButton.setObjectName("editButton")
        self.buttons_layout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.deleteButton.setObjectName("deleteButton")
        self.buttons_layout.addWidget(self.deleteButton)

        self.col_1.addLayout(self.buttons_layout)
        self.master_layout.addLayout(self.col_1)

        # Adding the central widget to the window
        MainWindow.setCentralWidget(self.centralwidget)

        # Connect buttons to their actions (assuming methods like add_newRecord exist)
        self.addButton.clicked.connect(self.add_newRecord)
        self.editButton.clicked.connect(self.editRecord)
        self.deleteButton.clicked.connect(self.deleteRecord)

    def retranslateUi(self, MainWindow):
        """
        Sets the textual content for UI elements.

        Parameters:
            MainWindow (QMainWindow): The main window that holds all the UI elements.
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Window"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.filterCheckBox.setText(_translate("MainWindow", "Enable Filter"))
        self.sizeLabel.setText(_translate("MainWindow", "Size"))
        self.brandLabel.setText(_translate("MainWindow", "Brand"))
        self.countryLabel.setText(_translate("MainWindow", "Country"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.stockLabel.setText(_translate("MainWindow", "Stock"))
        self.addButton.setText(_translate("MainWindow", "Add Record"))
        self.editButton.setText(_translate("MainWindow", "Edit Record"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Record"))
